version: '3'
services:
  redisedge:
    build: ./redisedge
    ports:
      - 6379:6379
  droneapp57:
    build: ./app
    depends_on:
      - redisedge
    command: ['init.py', '--url', 'redis://redisedge:6379']